# Generated by Django 5.2.8 on 2025-12-04 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='rut_solicitante',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El RUT debe ser sin puntos y con guión (Ej: 12345678-9)', regex='^\\d{7,8}-[0-9kK]$')]),
        ),
    ]
