# Generated by Django 5.2.8 on 2025-12-04 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_alter_reserva_rut_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Formato inválido.', regex='^\\d{7,8}-[0-9kK]$')])),
                ('motivo', models.CharField(choices=[('CANCELAR', 'Cancelar una reservación'), ('PROBLEMA', 'Informar un problema con sala/PC'), ('OTRO', 'Otro asunto')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut_solicitante',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Formato inválido.', regex='^\\d{7,8}-[0-9kK]$')]),
        ),
    ]
